/**
* EaselJS
* Visit http://easeljs.com/ for documentation, updates and examples.
*
* Copyright (c) 2011 Grant Skinner
* 
* Permission is hereby granted, free of charge, to any person
* obtaining a copy of this software and associated documentation
* files (the "Software"), to deal in the Software without
* restriction, including without limitation the rights to use,
* copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the
* Software is furnished to do so, subject to the following
* conditions:
* 
* The above copyright notice and this permission notice shall be
* included in all copies or substantial portions of the Software.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
* OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
* HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
* WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
**/
(function(l){UID=function(){throw"UID cannot be instantiated";};UID._nextID=0;UID.get=function(){return UID._nextID++};l.UID=UID})(window);(function(l){Ticker=function(){throw"Ticker cannot be instantiated.";};Ticker._listeners=[];Ticker._pauseable=[];Ticker._paused=!1;Ticker._inited=!1;Ticker._startTime=0;Ticker._pausedTime=0;Ticker._ticks=0;Ticker._pausedTickers=0;Ticker._interval=50;Ticker._intervalID=null;Ticker._lastTime=0;Ticker._times=[];Ticker.addListener=function(b,a){if(!Ticker._inited)Ticker._inited=!0,Ticker.setInterval(Ticker._interval);this.removeListener(b);Ticker._pauseable[Ticker._listeners.length]=a==null?!0:a;Ticker._listeners.push(b)};
Ticker.removeListener=function(b){Ticker._listeners!=null&&(b=Ticker._listeners.indexOf(b),b!=-1&&(Ticker._listeners.splice(b,1),Ticker._pauseable.splice(b,1)))};Ticker.removeAllListeners=function(){Ticker._listeners=[];Ticker._pauseable=[]};Ticker.setInterval=function(b){Ticker._intervalID!=null&&clearInterval(Ticker._intervalID);Ticker._lastTime=Ticker._getTime();Ticker._interval=b;Ticker._intervalID=setInterval(Ticker._tick,b)};Ticker.getInterval=function(){return Ticker._interval};Ticker.getFPS=
function(){return 1E3/Ticker._interval};Ticker.setFPS=function(b){Ticker.setInterval(1E3/b)};Ticker.getMeasuredFPS=function(b){if(Ticker._times.length<2)return-1;b==null&&(b=Ticker.getFPS()>>1);b=Math.min(Ticker._times.length-1,b);return 1E3/((Ticker._times[0]-Ticker._times[b])/b)};Ticker.setPaused=function(b){Ticker._paused=b};Ticker.getPaused=function(){return Ticker._paused};Ticker.getTime=function(b){return Ticker._getTime()-Ticker._startTime-(b?Ticker._pausedTime:0)};Ticker.getTicks=function(b){return Ticker._ticks-
(b?Ticker._pausedTickers:0)};Ticker._tick=function(){Ticker._ticks++;var b=Ticker.getTime(!1),a=b-Ticker._lastTime,t=Ticker._paused;t&&(Ticker._pausedTickers++,Ticker._pausedTime+=a);Ticker._lastTime=b;for(var c=Ticker._pauseable,d=Ticker._listeners,e=d?d.length:0,g=0;g<e;g++){var h=c[g],i=d[g];i==null||t&&h||i.tick==null||i.tick(a)}Ticker._times.unshift(b);Ticker._times.length>100&&Ticker._times.pop()};Ticker._getTime=function(){return(new Date).getTime()};Ticker._startTime=Ticker._getTime();l.Ticker=
Ticker})(window);(function(l){MouseEvent=function(a,b,c){this.initialize(a,b,c)};var b=MouseEvent.prototype;b.stageX=0;b.stageY=0;b.type=null;b.onMouseMove=null;b.onMouseUp=null;b.initialize=function(a,b,c){this.type=a;this.stageX=b;this.stageY=c};b.clone=function(){return new MouseEvent(this.type,this.stageX,this.stageY)};b.toString=function(){return"[MouseEvent (type="+this.type+" stageX="+this.stageX+" stageY="+this.stageY+")]"};l.MouseEvent=MouseEvent})(window);(function(l){Matrix2D=function(a,b,c,d,e,g){this.initialize(a,b,c,d,e,g)};var b=Matrix2D.prototype;Matrix2D.identity=null;Matrix2D.DEG_TO_RAD=Math.PI/180;b.a=1;b.b=0;b.c=0;b.d=1;b.tx=0;b.ty=0;b.alpha=1;b.shadow=null;b.compositeOperation=null;b.initialize=function(a,b,c,d,e,g){if(a!=null)this.a=a;if(b!=null)this.b=b;if(c!=null)this.c=c;if(d!=null)this.d=d;if(e!=null)this.tx=e;if(g!=null)this.ty=g};b.prepend=function(a,b,c,d,e,g){var h=this.tx;if(a!=1||b!=0||c!=0||d!=1){var i=this.a,j=this.c;this.a=
i*a+this.b*c;this.b=i*b+this.b*d;this.c=j*a+this.d*c;this.d=j*b+this.d*d}this.tx=h*a+this.ty*c+e;this.ty=h*b+this.ty*d+g};b.append=function(a,b,c,d,e,g){var h=this.a,i=this.b,j=this.c,k=this.d;this.a=a*h+b*j;this.b=a*i+b*k;this.c=c*h+d*j;this.d=c*i+d*k;this.tx=e*h+g*j+this.tx;this.ty=e*i+g*k+this.ty};b.prependMatrix=function(a){this.prepend(a.a,a.b,a.c,a.d,a.tx,a.ty);this.prependProperties(a.alpha,a.shadow,a.compositeOperation)};b.appendMatrix=function(a){this.append(a.a,a.b,a.c,a.d,a.tx,a.ty);this.appendProperties(a.alpha,
a.shadow,a.compositeOperation)};b.prependTransform=function(a,b,c,d,e,g,h,i,j){if(e%360)var k=e*Matrix2D.DEG_TO_RAD,e=Math.cos(k),k=Math.sin(k);else e=1,k=0;if(i||j)this.tx-=i,this.ty-=j;g||h?(g*=Matrix2D.DEG_TO_RAD,h*=Matrix2D.DEG_TO_RAD,this.prepend(e*c,k*c,-k*d,e*d,0,0),this.prepend(Math.cos(h),Math.sin(h),-Math.sin(g),Math.cos(g),a,b)):this.prepend(e*c,k*c,-k*d,e*d,a,b)};b.appendTransform=function(a,b,c,d,e,g,h,i,j){if(e%360)var k=e*Matrix2D.DEG_TO_RAD,e=Math.cos(k),k=Math.sin(k);else e=1,k=0;
g||h?(g*=Matrix2D.DEG_TO_RAD,h*=Matrix2D.DEG_TO_RAD,this.append(Math.cos(h),Math.sin(h),-Math.sin(g),Math.cos(g),a,b),this.append(e*c,k*c,-k*d,e*d,0,0)):this.append(e*c,k*c,-k*d,e*d,a,b);if(i||j)this.tx-=i*this.a+j*this.c,this.ty-=i*this.b+j*this.d};b.rotate=function(a){var b=Math.cos(a),a=Math.sin(a),c=this.a,d=this.c,e=this.tx;this.a=c*b-this.b*a;this.b=c*a+this.b*b;this.c=d*b-this.d*a;this.d=d*a+this.d*b;this.tx=e*b-this.ty*a;this.ty=e*a+this.ty*b};b.skew=function(a,b){a*=Matrix2D.DEG_TO_RAD;b*=
Matrix2D.DEG_TO_RAD;this.append(Math.cos(b),Math.sin(b),-Math.sin(a),Math.cos(a),0,0)};b.scale=function(a,b){this.a*=a;this.d*=b;this.tx*=a;this.ty*=b};b.translate=function(a,b){this.tx+=a;this.ty+=b};b.identity=function(){this.alpha=this.a=this.d=1;this.b=this.c=this.tx=this.ty=0;this.shadow=this.compositeOperation=null};b.invert=function(){var a=this.a,b=this.b,c=this.c,d=this.d,e=this.tx,g=a*d-b*c;this.a=d/g;this.b=-b/g;this.c=-c/g;this.d=a/g;this.tx=(c*this.ty-d*e)/g;this.ty=-(a*this.ty-b*e)/
g};b.decompose=function(a){a==null&&(a={});a.x=this.tx;a.y=this.ty;a.scaleX=Math.sqrt(this.a*this.a+this.b*this.b);a.scaleY=Math.sqrt(this.c*this.c+this.d*this.d);var b=Math.atan2(-this.c,this.d),c=Math.atan2(this.b,this.a);b==c?(a.rotation=c/Matrix2D.DEG_TO_RAD,this.a<0&&this.d>=0&&(a.rotation+=a.rotation<=0?180:-180),a.skewX=a.skewY=0):(a.skewX=b/Matrix2D.DEG_TO_RAD,a.skewY=c/Matrix2D.DEG_TO_RAD);return a};b.appendProperties=function(a,b,c){this.alpha*=a;this.shadow=b||this.shadow;this.compositeOperation=
c||this.compositeOperation};b.prependProperties=function(a,b,c){this.alpha*=a;this.shadow=this.shadow||b;this.compositeOperation=this.compositeOperation||c};b.clone=function(){var a=new Matrix2D(this.a,this.b,this.c,this.d,this.tx,this.ty);a.shadow=this.shadow;a.alpha=this.alpha;a.compositeOperation=this.compositeOperation;return a};b.toString=function(){return"[Matrix2D (a="+this.a+" b="+this.b+" c="+this.c+" d="+this.d+" tx="+this.tx+" ty="+this.ty+")]"};Matrix2D.identity=new Matrix2D(1,0,0,1,0,
0);l.Matrix2D=Matrix2D})(window);(function(l){Point=function(a,b){this.initialize(a,b)};var b=Point.prototype;b.x=0;b.y=0;b.initialize=function(a,b){this.x=a==null?0:a;this.y=b==null?0:b};b.clone=function(){return new Point(this.x,this.y)};b.toString=function(){return"[Point (x="+this.x+" y="+this.y+")]"};l.Point=Point})(window);(function(l){Rectangle=function(a,b,c,d){this.initialize(a,b,c,d)};var b=Rectangle.prototype;b.x=0;b.y=0;b.width=0;b.height=0;b.initialize=function(a,b,c,d){this.x=a==null?0:a;this.y=b==null?0:b;this.width=c==null?0:c;this.height=d==null?0:d};b.clone=function(){return new Rectangle(this.x,this.y,this.width,this.height)};b.toString=function(){return"[Rectangle (x="+this.x+" y="+this.y+" width="+this.width+" height="+this.height+")]"};l.Rectangle=Rectangle})(window);(function(l){Shadow=function(a,b,c,d){this.initialize(a,b,c,d)};var b=Shadow.prototype;Shadow.identity=null;b.color=null;b.offsetX=0;b.offsetY=0;b.blur=0;b.initialize=function(a,b,c,d){this.color=a;this.offsetX=b;this.offsetY=c;this.blur=d};b.toString=function(){return"[Shadow]"};b.clone=function(){return new Shadow(this.color,this.offsetX,this.offsetY,this.blur)};Shadow.identity=new Shadow(null,0,0,0);l.Shadow=Shadow})(window);(function(l){SpriteSheet=function(a,b,c,d){this.initialize(a,b,c,d)};var b=SpriteSheet.prototype;b.image=null;b.frameWidth=0;b.frameHeight=0;b.frameData=null;b.loop=!0;b.totalFrames=0;b.initialize=function(a,b,c,d){this.image=a;this.frameWidth=b;this.frameHeight=c;this.frameData=d};b.toString=function(){return"[SpriteSheet]"};b.clone=function(){var a=new SpriteSheet(this.image,this.frameWidth,this.frameHeight,this.frameData);a.loop=this.loop;a.totalFrames=this.totalFrames;return a};l.SpriteSheet=
SpriteSheet})(window);(function(l){function b(a,b){this.f=a;this.params=b}b.prototype.exec=function(a){this.f.apply(a,this.params)};Graphics=function(a){this.initialize(a)};var a=Graphics.prototype;Graphics.getRGB=function(a,b,d,e){a!=null&&d==null&&(e=b,d=a&255,b=a>>8&255,a=a>>16&255);return e==null?"rgb("+a+","+b+","+d+")":"rgba("+a+","+b+","+d+","+e+")"};Graphics.getHSL=function(a,b,d,e){return e==null?"hsl("+a%360+","+b+"%,"+d+"%)":"hsla("+a%360+","+b+"%,"+d+"%,"+e+")"};Graphics.STROKE_CAPS_MAP=["butt","round","square"];
Graphics.STROKE_JOINTS_MAP=["miter","round","bevel"];Graphics._getCanvasContext=f=function(){if(typeof G_vmlCanvasManager!=="undefined"){var a=document.createElement("canvas");G_vmlCanvasManager.initElement(a);return a.getContext("2d")}else return document.createElement("canvas").getContext("2d")};Graphics._ctx=Graphics._getCanvasContext();Graphics.beginCmd=new b(Graphics._ctx.beginPath,[]);Graphics.fillCmd=new b(Graphics._ctx.fill,[]);Graphics.strokeCmd=new b(Graphics._ctx.stroke,[]);a._strokeInstructions=
null;a._strokeStyleInstructions=null;a._fillInstructions=null;a._instructions=null;a._oldInstructions=null;a._activeInstructions=null;a._active=!1;a._dirty=!1;a.initialize=function(a){this.clear();this._ctx=Graphics._ctx;with(this)eval(a)};a.draw=function(a){this._dirty&&this._updateInstructions();for(var b=this._instructions,d=0,e=b.length;d<e;d++)b[d].exec(a)};a.moveTo=function(a,c){this._activeInstructions.push(new b(this._ctx.moveTo,[a,c]));return this};a.lineTo=function(a,c){this._dirty=this._active=
!0;this._activeInstructions.push(new b(this._ctx.lineTo,[a,c]));return this};a.arcTo=function(a,c,d,e,g){this._dirty=this._active=!0;this._activeInstructions.push(new b(this._ctx.arcTo,[a,c,d,e,g]));return this};a.arc=function(a,c,d,e,g,h){this._dirty=this._active=!0;h==null&&(h=!1);this._activeInstructions.push(new b(this._ctx.arc,[a,c,d,e,g,h]));return this};a.quadraticCurveTo=function(a,c,d,e){this._dirty=this._active=!0;this._activeInstructions.push(new b(this._ctx.quadraticCurveTo,[a,c,d,e]));
return this};a.bezierCurveTo=function(a,c,d,e,g,h){this._dirty=this._active=!0;this._activeInstructions.push(new b(this._ctx.bezierCurveTo,[a,c,d,e,g,h]));return this};a.rect=function(a,c,d,e){this._dirty=this._active=!0;this._activeInstructions.push(new b(this._ctx.rect,[a,c,d-1,e]));return this};a.closePath=function(){if(this._active)this._dirty=!0,this._activeInstructions.push(new b(this._ctx.closePath,[]));return this};a.clear=function(){this._instructions=[];this._oldInstructions=[];this._activeInstructions=
[];this._strokeStyleInstructions=this._strokeInstructions=this._fillInstructions=null;this._active=this._dirty=!1;return this};a.beginFill=function(a){this._active&&this._newPath();this._fillInstructions=a?[new b(this._setProp,["fillStyle",a])]:null;return this};a.beginLinearGradientFill=function(a,c,d,e,g,h){this._active&&this._newPath();d=this._ctx.createLinearGradient(d,e,g,h);e=0;for(g=a.length;e<g;e++)d.addColorStop(c[e],a[e]);this._fillInstructions=[new b(this._setProp,["fillStyle",d])];return this};
a.beginRadialGradientFill=function(a,c,d,e,g,h,i,j){this._active&&this._newPath();d=this._ctx.createRadialGradient(d,e,g,h,i,j);e=0;for(g=a.length;e<g;e++)d.addColorStop(c[e],a[e]);this._fillInstructions=[new b(this._setProp,["fillStyle",d])];return this};a.beginBitmapFill=function(a,c){this._active&&this._newPath();var d=this._ctx.createPattern(a,c||"");this._fillInstructions=[new b(this._setProp,["fillStyle",d])];return this};a.endFill=function(){this.beginFill(null);return this};a.setStrokeStyle=
function(a,c,d,e){this._active&&this._newPath();this._strokeStyleInstructions=[new b(this._setProp,["lineWidth",a==null?"1":a]),new b(this._setProp,["lineCap",c==null?"butt":isNaN(c)?c:Graphics.STROKE_CAPS_MAP[c]]),new b(this._setProp,["lineJoin",d==null?"miter":isNaN(d)?d:Graphics.STROKE_JOINTS_MAP[d]]),new b(this._setProp,["miterLimit",e==null?"10":e])];return this};a.beginStroke=function(a){this._active&&this._newPath();this._strokeInstructions=a?[new b(this._setProp,["strokeStyle",a])]:null;return this};
a.beginLinearGradientStroke=function(a,c,d,e,g,h){this._active&&this._newPath();d=this._ctx.createLinearGradient(d,e,g,h);e=0;for(g=a.length;e<g;e++)d.addColorStop(c[e],a[e]);this._strokeInstructions=[new b(this._setProp,["strokeStyle",d])];return this};a.beginRadialGradientStroke=function(a,c,d,e,g,h,i,j){this._active&&this._newPath();d=this._ctx.createRadialGradient(d,e,g,h,i,j);e=0;for(g=a.length;e<g;e++)d.addColorStop(c[e],a[e]);this._strokeInstructions=[new b(this._setProp,["strokeStyle",d])];
return this};a.beginBitmapStroke=function(a,c){this._active&&this._newPath();var d=this._ctx.createPattern(a,c||"");this._strokeInstructions=[new b(this._setProp,["strokeStyle",d])];return this};a.endStroke=function(){this.beginStroke(null);return this};a.curveTo=a.quadraticCurveTo;a.drawRect=a.rect;a.drawRoundRect=function(a,b,d,e,g){this.drawRoundRectComplex(a,b,d,e,g,g,g,g);return this};a.drawRoundRectComplex=function(a,c,d,e,g,h,i,j){this._dirty=this._active=!0;this._activeInstructions.push(new b(this._ctx.moveTo,
[a+g,c]),new b(this._ctx.lineTo,[a+d-h,c]),new b(this._ctx.arc,[a+d-h,c+h,h,-Math.PI/2,0,!1]),new b(this._ctx.lineTo,[a+d,c+e-i]),new b(this._ctx.arc,[a+d-i,c+e-i,i,0,Math.PI/2,!1]),new b(this._ctx.lineTo,[a+j,c+e]),new b(this._ctx.arc,[a+j,c+e-j,j,Math.PI/2,Math.PI,!1]),new b(this._ctx.lineTo,[a,c+g]),new b(this._ctx.arc,[a+g,c+g,g,Math.PI,Math.PI*3/2,!1]));return this};a.drawCircle=function(a,b,d){this.arc(a,b,d,0,Math.PI*2);return this};a.drawEllipse=function(a,c,d,e){this._dirty=this._active=
!0;var g=d/2*0.5522848,h=e/2*0.5522848,i=a+d,j=c+e,d=a+d/2,e=c+e/2;this._activeInstructions.push(new b(this._ctx.moveTo,[a,e]),new b(this._ctx.bezierCurveTo,[a,e-h,d-g,c,d,c]),new b(this._ctx.bezierCurveTo,[d+g,c,i,e-h,i,e]),new b(this._ctx.bezierCurveTo,[i,e+h,d+g,j,d,j]),new b(this._ctx.bezierCurveTo,[d-g,j,a,e+h,a,e]));return this};a.drawPolyStar=function(a,c,d,e,g,h){this._dirty=this._active=!0;g==null&&(g=0);g=1-g;h==null?h=0:h/=180/Math.PI;var i=Math.PI/e;this._activeInstructions.push(new b(this._ctx.moveTo,
[a+Math.cos(h)*d,c+Math.sin(h)*d]));for(var j=0;j<e;j++)h+=i,g!=1&&this._activeInstructions.push(new b(this._ctx.lineTo,[a+Math.cos(h)*d*g,c+Math.sin(h)*d*g])),h+=i,this._activeInstructions.push(new b(this._ctx.lineTo,[a+Math.cos(h)*d,c+Math.sin(h)*d]));return this};a.clone=function(){var a=new Graphics;a._instructions=this._instructions.slice();a._activeInstructions=this._activeInstructions.slice();a._oldInstructions=this._oldInstructions.slice();if(this._fillInstructions)a._fillInstructions=this._fillInstructions.slice();
if(this._strokeInstructions)a._strokeInstructions=this._strokeInstructions.slice();if(this._strokeStyleInstructions)a._strokeStyleInstructions=this._strokeStyleInstructions.slice();a._active=this._active;a._dirty=this._dirty;return a};a.toString=function(){return"[Graphics]"};a.mt=a.moveTo;a.lt=a.lineTo;a.at=a.arcTo;a.bt=a.bezierCurveTo;a.qt=a.quadraticCurveTo;a.a=a.arc;a.r=a.rect;a.cp=a.closePath;a.c=a.clear;a.f=a.beginFill;a.lf=a.beginLinearGradientFill;a.rf=a.beginRadialGradientFill;a.bf=a.beginBitmapFill;
a.ef=a.endFill;a.ss=a.setStrokeStyle;a.s=a.beginStroke;a.ls=a.beginLinearGradientStroke;a.rs=a.beginRadialGradientStroke;a.bs=a.beginBitmapStroke;a.es=a.endStroke;a.dr=a.drawRect;a.rr=a.drawRoundRect;a.rc=a.drawRoundRectComplex;a.dc=a.drawCircle;a.de=a.drawEllipse;a.dp=a.drawPolyStar;a._updateInstructions=function(){this._instructions=this._oldInstructions.slice();this._instructions.push(Graphics.beginCmd);this._fillInstructions&&this._instructions.push.apply(this._instructions,this._fillInstructions);
this._strokeInstructions&&(this._instructions.push.apply(this._instructions,this._strokeInstructions),this._strokeStyleInstructions&&this._instructions.push.apply(this._instructions,this._strokeStyleInstructions));this._instructions.push.apply(this._instructions,this._activeInstructions);this._fillInstructions&&this._instructions.push(Graphics.fillCmd);this._strokeInstructions&&this._instructions.push(Graphics.strokeCmd)};a._newPath=function(){this._dirty&&this._updateInstructions();this._oldInstructions=
this._instructions;this._activeInstructions=[];this._active=this._dirty=!1};a._setProp=function(a,b){this[a]=b};l.Graphics=Graphics})(window);(function(l){DisplayObject=function(){this.initialize()};var b=DisplayObject.prototype;DisplayObject.suppressCrossDomainErrors=!1;DisplayObject._getHitTestCanvas=function(){if(typeof G_vmlCanvasManager!=="undefined"){var a=document.createElement("canvas");G_vmlCanvasManager.initElement(a);return a}else return document.createElement("canvas")};DisplayObject._hitTestCanvas=DisplayObject._getHitTestCanvas();DisplayObject._hitTestCanvas.width=DisplayObject._hitTestCanvas.height=1;DisplayObject._hitTestContext=
DisplayObject._hitTestCanvas.getContext("2d");DisplayObject._workingMatrix=new Matrix2D;b.alpha=1;b.cacheCanvas=null;b.id=-1;b.mouseEnabled=!0;b.name=null;b.parent=null;b.regX=0;b.regY=0;b.rotation=0;b.scaleX=1;b.scaleY=1;b.skewX=0;b.skewY=0;b.shadow=null;b.visible=!0;b.x=0;b.y=0;b.compositeOperation=null;b.snapToPixel=!1;b.onPress=null;b.onClick=null;b.onMouseOver=null;b.onMouseOut=null;b._cacheOffsetX=0;b._cacheOffsetY=0;b._cacheDraw=!1;b._activeContext=null;b._restoreContext=!1;b._revertShadow=
!1;b._revertX=0;b._revertY=0;b._revertAlpha=1;b.initialize=function(){this.id=UID.get();this.children=[]};b.isVisible=function(){return this.visible&&this.alpha>0&&this.scaleX!=0&&this.scaleY!=0};b.draw=function(a,b){if(b||!this.cacheCanvas)return!1;a.translate(this._cacheOffsetX,this._cacheOffsetY);a.drawImage(this.cacheCanvas,0,0);a.translate(-this._cacheOffsetX,-this._cacheOffsetY);return!0};b.cache=function(a,b,c,d){var e;if(this.cacheCanvas==null)this.cacheCanvas=document.createElement("canvas");
e=this.cacheCanvas.getContext("2d");this.cacheCanvas.width=c;this.cacheCanvas.height=d;e.setTransform(1,0,0,1,-a,-b);e.clearRect(0,0,c+1,d+1);this.draw(e,!0);this._cacheOffsetX=a;this._cacheOffsetY=b};b.updateCache=function(a){if(this.cacheCanvas==null)throw"cache() must be called before updateCache()";var b=this.cacheCanvas.getContext("2d");b.setTransform(1,0,0,1,-this._cacheOffsetX,-this._cacheOffsetY);a?b.globalCompositeOperation=a:b.clearRect(0,0,this.cacheCanvas.width+1,this.cacheCanvas.height+
1);this.draw(b,!0);if(a)b.globalCompositeOperation="source-over"};b.uncache=function(){this.cacheCanvas=null;this.cacheOffsetX=this.cacheOffsetY=0};b.getStage=function(){for(var a=this;a.parent;)a=a.parent;return a instanceof Stage?a:null};b.localToGlobal=function(a,b){var c=this.getConcatenatedMatrix();if(c==null)return null;c.append(1,0,0,1,a,b);return new Point(c.tx,c.ty)};b.globalToLocal=function(a,b){var c=this.getConcatenatedMatrix();if(c==null)return null;c.invert();c.append(1,0,0,1,a,b);return new Point(c.tx,
c.ty)};b.localToLocal=function(a,b,c){a=this.localToGlobal(a,b);return c.globalToLocal(a.x,a.y)};b.getConcatenatedMatrix=function(a){a?a.identity():a=new Matrix2D;for(var b=this;b!=null;)a.prependTransform(b.x,b.y,b.scaleX,b.scaleY,b.rotation,b.skewX,b.skewY,b.regX,b.regY),a.prependProperties(b.alpha,b.shadow,b.compositeOperation),b=b.parent;return a};b.hitTest=function(a,b){var c=DisplayObject._hitTestContext,d=DisplayObject._hitTestCanvas;c.setTransform(1,0,0,1,-a,-b);this.draw(c);c=this._testHit(c);
d.width=0;d.width=1;return c};b.clone=function(){var a=new DisplayObject;this.cloneProps(a);return a};b.toString=function(){return"[DisplayObject (name="+this.name+")]"};b.cloneProps=function(a){a.alpha=this.alpha;a.name=this.name;a.regX=this.regX;a.regY=this.regY;a.rotation=this.rotation;a.scaleX=this.scaleX;a.scaleY=this.scaleY;a.shadow=this.shadow;a.skewX=this.skewX;a.skewY=this.skewY;a.visible=this.visible;a.x=this.x;a.y=this.y;a.mouseEnabled=this.mouseEnabled;a.compositeOperation=this.compositeOperation};
b.applyShadow=function(a,b){b=b||Shadow.identity;a.shadowColor=b.color;a.shadowOffsetX=b.offsetX;a.shadowOffsetY=b.offsetY;a.shadowBlur=b.blur};b._testHit=function(a){try{var b=a.getImageData(0,0,1,1).data[3]>1}catch(c){if(!DisplayObject.suppressCrossDomainErrors)throw"An error has occured. This is most likely due to security restrictions on reading canvas pixel data with local or cross-domain images.";}return b};l.DisplayObject=DisplayObject})(window);(function(l){Container=function(){this.initialize()};var b=Container.prototype=new DisplayObject;b.children=null;b.DisplayObject_initialize=b.initialize;b.initialize=function(){this.DisplayObject_initialize();this.children=[]};b.isVisible=function(){return this.visible&&this.alpha>0&&this.children.length&&this.scaleX!=0&&this.scaleY!=0};b.DisplayObject_draw=b.draw;b.draw=function(a,b,c){var d=Stage._snapToPixelEnabled;c||(c=new Matrix2D,c.appendProperties(this.alpha,this.shadow,this.compositeOperation));
if(this.DisplayObject_draw(a,b))return!0;for(var b=this.children.length,e=this.children.slice(0),g=0;g<b;g++){var h=e[g];h.tick&&h.tick();if(h.isVisible()){var i=!1,j=c.clone();j.appendTransform(h.x,h.y,h.scaleX,h.scaleY,h.rotation,h.skewX,h.skewY,h.regX,h.regY);j.appendProperties(h.alpha,h.shadow,h.compositeOperation);if(!(h instanceof Container))d&&h.snapToPixel&&j.a==1&&j.b==0&&j.c==0&&j.d==1?a.setTransform(j.a,j.b,j.c,j.d,j.tx+0.5|0,j.ty+0.5|0):a.setTransform(j.a,j.b,j.c,j.d,j.tx,j.ty),a.globalAlpha=
j.alpha,a.globalCompositeOperation=j.compositeOperation||"source-over",(i=j.shadow)&&this.applyShadow(a,i);h.draw(a,!1,j);i&&this.applyShadow(a)}}return!0};b.addChild=function(a){var b=arguments.length;if(b>1){for(var c=0;c<b;c++)this.addChild(arguments[c]);return arguments[b-1]}a.parent&&a.parent.removeChild(a);a.parent=this;this.children.push(a);return a};b.addChildAt=function(a,b){var c=arguments.length;if(c>2){for(var b=arguments[d-1],d=0;d<c-1;d++)this.addChildAt(arguments[d],b+d);return arguments[c-
2]}a.parent&&a.parent.removeChild(a);a.parent=this;this.children.splice(b,0,a);return a};b.removeChild=function(a){var b=arguments.length;if(b>1){for(var c=!0,d=0;d<b;d++)c=c&&this.removeChild(arguments[d]);return c}return this.removeChildAt(this.children.indexOf(a))};b.removeChildAt=function(a){var b=arguments.length;if(b>1){for(var c=[],d=0;d<b;d++)c[d]=arguments[d];c.sort(function(a,b){return b-a});for(var e=!0,d=0;d<b;d++)e=e&&this.removeChildAt(c[d]);return e}if(a<0||a>this.children.length-1)return!1;
b=this.children[a];if(b!=null)b.parent=null;this.children.splice(a,1);return!0};b.removeAllChildren=function(){for(;this.children.length;)this.removeChildAt(0)};b.getChildAt=function(a){return this.children[a]};b.sortChildren=function(a){this.children.sort(a)};b.getChildIndex=function(a){return this.children.indexOf(a)};b.getNumChildren=function(){return this.children.length};b.contains=function(a){for(;a;){if(a==this)return!0;a=a.parent}return!1};b.hitTest=function(a,b){return this.getObjectUnderPoint(a,
b)!=null};b.getObjectsUnderPoint=function(a,b){var c=[],d=this.localToGlobal(a,b);this._getObjectsUnderPoint(d.x,d.y,c);return c};b.getObjectUnderPoint=function(a,b){var c=this.localToGlobal(a,b);return this._getObjectsUnderPoint(c.x,c.y)};b.clone=function(a){var b=new Container;this.cloneProps(b);if(a)for(var c=b.children=[],d=0,e=this.children.length;d<e;d++)c.push(this.children[d].clone(a));return b};b.toString=function(){return"[Container (name="+this.name+")]"};b._getObjectsUnderPoint=function(a,
b,c,d){var e=DisplayObject._hitTestContext,g=DisplayObject._hitTestCanvas,h=DisplayObject._workingMatrix,i=d&1&&(this.onPress||this.onClick)||d&2&&(this.onMouseOver||this.onMouseOut);if(this.cacheCanvas)if(this.getConcatenatedMatrix(h),e.setTransform(h.a,h.b,h.c,h.d,h.tx-a,h.ty-b),e.globalAlpha=h.alpha,this.draw(e),this._testHit(e)){if(g.width=0,g.width=1,i)return this}else return null;for(var j=this.children.length-1;j>=0;j--){var k=this.children[j];if(k.isVisible()&&k.mouseEnabled)if(k instanceof
Container)if(i){if(k=k._getObjectsUnderPoint(a,b))return this}else{if(k=k._getObjectsUnderPoint(a,b,c,d),!c&&k)return k}else if(!d||i||d&1&&(k.onPress||k.onClick)||d&2&&(k.onMouseOver||k.onMouseOut))if(k.getConcatenatedMatrix(h),e.setTransform(h.a,h.b,h.c,h.d,h.tx-a,h.ty-b),e.globalAlpha=h.alpha,k.draw(e),this._testHit(e))if(g.width=0,g.width=1,i)return this;else if(c)c.push(k);else return k}return null};l.Container=Container})(window);(function(l){Stage=function(a){this.initialize(a)};var b=Stage.prototype=new Container;Stage._snapToPixelEnabled=!1;b.autoClear=!0;b.canvas=null;b.mouseX=null;b.mouseY=null;b.onMouseMove=null;b.onMouseUp=null;b.onMouseDown=null;b.snapToPixelEnabled=!1;b.mouseInBounds=!1;b._tmpCanvas=null;b._activeMouseEvent=null;b._activeMouseTarget=null;b._mouseOverIntervalID=null;b._mouseOverX=0;b._mouseOverY=0;b._mouseOverTarget=null;b.Container_initialize=b.initialize;b.initialize=function(a){this.Container_initialize();
this.canvas=a;this.mouseChildren=!0;var b=this;l.addEventListener?(l.addEventListener("mouseup",function(a){b._handleMouseUp(a)},!1),l.addEventListener("mousemove",function(a){b._handleMouseMove(a)},!1)):document.addEventListener&&(document.addEventListener("mouseup",function(a){b._handleMouseUp(a)},!1),document.addEventListener("mousemove",function(a){b._handleMouseMove(a)},!1));a.addEventListener?a.addEventListener("mousedown",function(a){b._handleMouseDown(a)},!1):a.attachEvent("mousedown",function(a){b._handleMouseDown(a)},
!1)};b.update=function(){if(this.canvas)this.autoClear&&this.clear(),Stage._snapToPixelEnabled=this.snapToPixelEnabled,this.draw(this.canvas.getContext("2d"),!1,this.getConcatenatedMatrix(DisplayObject._workingMatrix))};b.tick=b.update;b.clear=function(){if(this.canvas){var a=this.canvas.getContext("2d");a.setTransform(1,0,0,1,0,0);a.clearRect(0,0,this.canvas.width,this.canvas.height)}};b.toDataURL=function(a,b){b||(b="image/png");var c=this.canvas.getContext("2d"),d=this.canvas.width,e=this.canvas.height,
g;if(a){g=c.getImageData(0,0,d,e);var h=c.globalCompositeOperation;c.globalCompositeOperation="destination-over";c.fillStyle=a;c.fillRect(0,0,d,e)}var i=this.canvas.toDataURL(b);if(a)c.clearRect(0,0,d,e),c.putImageData(g,0,0),c.globalCompositeOperation=h;return i};b.enableMouseOver=function(a){if(this._mouseOverIntervalID)clearInterval(this._mouseOverIntervalID),this._mouseOverIntervalID=null;if(!(a<=0)){var b=this;this._mouseOverIntervalID=setInterval(function(){b._testMouseOver()},1E3/Math.min(50,
a));this._mouseOverX=NaN;this._mouseOverTarget=null}};b.clone=function(){var a=new Stage(null);this.cloneProps(a);return a};b.toString=function(){return"[Stage (name="+this.name+")]"};b._handleMouseMove=function(a){if(this.canvas){if(!a)a=l.event;var b=this.mouseInBounds;this._updateMousePosition(a.pageX,a.pageY);if(b||this.mouseInBounds){a=new MouseEvent("onMouseMove",this.mouseX,this.mouseY);if(this.onMouseMove)this.onMouseMove(a);if(this._activeMouseEvent&&this._activeMouseEvent.onMouseMove)this._activeMouseEvent.onMouseMove(a)}}else this.mouseX=
this.mouseY=null};b._updateMousePosition=function(a,b){var c=this.canvas;do a-=c.offsetLeft,b-=c.offsetTop;while(c=c.offsetParent);if(this.mouseInBounds=a>=0&&b>=0&&a<this.canvas.width&&b<this.canvas.height)this.mouseX=a,this.mouseY=b};b._handleMouseUp=function(){var a=new MouseEvent("onMouseUp",this.mouseX,this.mouseY);if(this.onMouseUp)this.onMouseUp(a);if(this._activeMouseEvent&&this._activeMouseEvent.onMouseUp)this._activeMouseEvent.onMouseUp(a);if(this._activeMouseTarget&&this._activeMouseTarget.onClick&&
this._getObjectsUnderPoint(this.mouseX,this.mouseY,null,!0,this._mouseOverIntervalID?3:1)==this._activeMouseTarget)this._activeMouseTarget.onClick(new MouseEvent("onClick",this.mouseX,this.mouseY));this._activeMouseEvent=this.activeMouseTarget=null};b._handleMouseDown=function(){if(this.onMouseDown)this.onMouseDown(new MouseEvent("onMouseDown",this.mouseX,this.mouseY));var a=this._getObjectsUnderPoint(this.mouseX,this.mouseY,null,this._mouseOverIntervalID?3:1);if(a){if(a.onPress instanceof Function){var b=
new MouseEvent("onPress",this.mouseX,this.mouseY);a.onPress(b);if(b.onMouseMove||b.onMouseUp)this._activeMouseEvent=b}this._activeMouseTarget=a}};b._testMouseOver=function(){if(!(this.mouseX==this._mouseOverX&&this.mouseY==this._mouseOverY&&this.mouseInBounds)){var a=null;if(this.mouseInBounds)a=this._getObjectsUnderPoint(this.mouseX,this.mouseY,null,3),this._mouseOverX=this.mouseX,this._mouseOverY=this.mouseY;if(this._mouseOverTarget!=a){if(this._mouseOverTarget&&this._mouseOverTarget.onMouseOut)this._mouseOverTarget.onMouseOut(new MouseEvent("onMouseOver",
this.mouseX,this.mouseY));if(a&&a.onMouseOver)a.onMouseOver(new MouseEvent("onMouseOut",this.mouseX,this.mouseY));this._mouseOverTarget=a}}};l.Stage=Stage})(window);(function(l){Bitmap=function(a){this.initialize(a)};var b=Bitmap.prototype=new DisplayObject;b.image=null;b.snapToPixel=!0;b.DisplayObject_initialize=b.initialize;b.initialize=function(a){this.DisplayObject_initialize();this.image=a};b.isVisible=function(){return this.visible&&this.alpha>0&&this.scaleX!=0&&this.scaleY!=0&&this.image&&(this.image.complete||this.image.getContext)};b.DisplayObject_draw=b.draw;b.draw=function(a,b){if(this.DisplayObject_draw(a,b))return!0;a.drawImage(this.image,0,0);return!0};
b.clone=function(){var a=new Bitmap(this.image);this.cloneProps(a);return a};b.toString=function(){return"[Bitmap (name="+this.name+")]"};l.Bitmap=Bitmap})(window);(function(l){BitmapSequence=function(a){this.initialize(a)};var b=BitmapSequence.prototype=new DisplayObject;b.callback=null;b.currentFrame=-1;b.currentSequence=null;b.currentEndFrame=null;b.currentStartFrame=null;b.nextSequence=null;b.paused=!1;b.spriteSheet=null;b.snapToPixel=!0;b.DisplayObject_initialize=b.initialize;b.initialize=function(a){this.DisplayObject_initialize();this.spriteSheet=a};b.isVisible=function(){var a=this.spriteSheet?this.spriteSheet.image:null;return this.visible&&this.alpha>
0&&this.scaleX!=0&&this.scaleY!=0&&a&&this.currentFrame>=0&&(a.complete||a.getContext)};b.DisplayObject_draw=b.draw;b.draw=function(a,b){if(this.DisplayObject_draw(a,b))return!0;var c=this.spriteSheet.image,d=this.spriteSheet.frameWidth,e=this.spriteSheet.frameHeight,g=c.width/d|0,h=c.height/e|0;if(this.currentEndFrame!=null){if(this.currentFrame>this.currentEndFrame)this.nextSequence?this._goto(this.nextSequence):(this.paused=!0,this.currentFrame=this.currentEndFrame),this.callback&&this.callback(this)}else if(h=
this.spriteSheet.totalFrames||g*h,this.currentFrame>=h)this.spriteSheet.loop?this.currentFrame=0:(this.currentFrame=h-1,this.paused=!0),this.callback&&this.callback(this);this.currentFrame>=0&&a.drawImage(c,d*(this.currentFrame%g),e*(this.currentFrame/g|0),d,e,0,0,d,e);return!0};b.tick=function(){if(this.currentFrame==-1&&this.spriteSheet.frameData)this.paused=!0;this.paused||this.currentFrame++};b.gotoAndPlay=function(a){this.paused=!1;this._goto(a)};b.gotoAndStop=function(a){this.paused=!0;this._goto(a)};
b.clone=function(){var a=new BitmapSequence(this.spriteSheet);this.cloneProps(a);return a};b.toString=function(){return"[BitmapSequence (name="+this.name+")]"};b.DisplayObject_cloneProps=b.cloneProps;b.cloneProps=function(a){this.DisplayObject_cloneProps(a);a.callback=this.callback;a.currentFrame=this.currentFrame;a.currentStartFrame=this.currentStartFrame;a.currentEndFrame=this.currentEndFrame;a.currentSequence=this.currentSequence;a.nextSequence=this.nextSequence;a.paused=this.paused;a.frameData=
this.frameData};b._goto=function(a){if(isNaN(a))if(a==this.currentSequence)this.currentFrame=this.currentStartFrame;else{var b=this.spriteSheet.frameData[a];if(b instanceof Array){this.currentFrame=this.currentStartFrame=b[0];this.currentSequence=a;this.currentEndFrame=b[1];if(this.currentEndFrame==null)this.currentEndFrame=this.currentStartFrame;if(this.currentEndFrame==null)this.currentEndFrame=this.currentFrame;this.nextSequence=b[2];if(this.nextSequence==null)this.nextSequence=this.currentSequence;
else if(this.nextSequence==!1)this.nextSequence=null}else this.currentSequence=this.nextSequence=null,this.currentEndFrame=this.currentFrame=this.currentStartFrame=b}else this.currentSequence=this.nextSequence=this.currentEndFrame=null,this.currentStartFrame=0,this.currentFrame=a};l.BitmapSequence=BitmapSequence})(window);(function(l){Shape=function(a){this.initialize(a)};var b=Shape.prototype=new DisplayObject;b.graphics=null;b.DisplayObject_initialize=b.initialize;b.initialize=function(a){this.DisplayObject_initialize();this.graphics=a?a:new Graphics};b.isVisible=function(){return this.visible&&this.alpha>0&&this.scaleX!=0&&this.scaleY!=0&&this.graphics};b.DisplayObject_draw=b.draw;b.draw=function(a,b){if(this.DisplayObject_draw(a,b))return!0;this.graphics.draw(a);return!0};b.clone=function(a){a=new Shape(a&&this.graphics?
this.graphics.clone():this.graphics);this.cloneProps(a);return a};b.toString=function(){return"[Shape (name="+this.name+")]"};l.Shape=Shape})(window);(function(l){Text=function(a,b,c){this.initialize(a,b,c)};var b=Text.prototype=new DisplayObject;Text._getWorkingContext=function(){if(typeof G_vmlCanvasManager!=="undefined"){var a=document.createElement("canvas");G_vmlCanvasManager.initElement(a);return a.getContext("2d")}else return document.createElement("canvas").getContext("2d")};Text._workingContext=Text._getWorkingContext();b.text="";b.font=null;b.color=null;b.textAlign=null;b.textBaseline=null;b.maxWidth=null;b.outline=!1;b.lineHeight=null;
b.lineWidth=null;b.DisplayObject_initialize=b.initialize;b.initialize=function(a,b,c){this.DisplayObject_initialize();this.text=a;this.font=b;this.color=c?c:"#000"};b.isVisible=function(){return Boolean(this.visible&&this.alpha>0&&this.scaleX!=0&&this.scaleY!=0&&this.text!=null&&this.text!="")};b.DisplayObject_draw=b.draw;b.draw=function(a,b){if(this.DisplayObject_draw(a,b))return!0;this.outline?a.strokeStyle=this.color:a.fillStyle=this.color;a.font=this.font;a.textAlign=this.textAlign?this.textAlign:
"start";a.textBaseline=this.textBaseline?this.textBaseline:"alphabetic";for(var c=String(this.text).split(/(?:\r\n|\r|\n)/),d=this.lineHeight==null?this.getMeasuredLineHeight():this.lineHeight,e=0,g=0,h=c.length;g<h;g++){var i=a.measureText(c[g]).width;if(this.lineWidth==null||i<this.lineWidth)this._drawTextLine(a,c[g],e);else{for(var i=c[g].split(/(\s)/),j=i[0],k=1,l=i.length;k<l;k+=2)a.measureText(j+i[k]+i[k+1]).width>this.lineWidth?(this._drawTextLine(a,j,e),e+=d,j=i[k+1]):j+=i[k]+i[k+1];this._drawTextLine(a,
j,e)}e+=d}return!0};b.getMeasuredWidth=function(){return this._getWorkingContext().measureText(this.text).width};b.getMeasuredLineHeight=function(){return this._getWorkingContext().measureText("M").width*1.2};b.clone=function(){var a=new Text(this.text,this.font,this.color);this.cloneProps(a);return a};b.toString=function(){return"[Text (text="+(this.text.length>20?this.text.substr(0,17)+"...":this.text)+")]"};b.DisplayObject_cloneProps=b.cloneProps;b.cloneProps=function(a){this.DisplayObject_cloneProps(a);
a.textAlign=this.textAlign;a.textBaseline=this.textBaseline;a.maxWidth=this.maxWidth;a.outline=this.outline;a.lineHeight=this.lineHeight;a.lineWidth=this.lineWidth};b._getWorkingContext=function(){var a=Text._workingContext;a.font=this.font;a.textAlign=this.textAlign?this.textAlign:"start";a.textBaseline=this.textBaseline?this.textBaseline:"alphabetic";return a};b._drawTextLine=function(a,b,c){this.outline?a.strokeText(b,0,c,this.maxWidth):a.fillText(b,0,c,this.maxWidth)};l.Text=Text})(window);(function(l){SpriteSheetUtils=function(){throw"SpriteSheetUtils cannot be instantiated";};SpriteSheetUtils._getWorkingCanvas=function(){if(typeof G_vmlCanvasManager!=="undefined"){var b=document.createElement("canvas");G_vmlCanvasManager.initElement(b);return b}else return document.createElement("canvas")};SpriteSheetUtils._workingCanvas=SpriteSheetUtils._getWorkingCanvas();SpriteSheetUtils._workingContext=SpriteSheetUtils._workingCanvas.getContext("2d");SpriteSheetUtils.flip=function(b,a){var l=
b.image,c=b.frameData,d=b.frameWidth,e=b.frameHeight,g=l.width/d|0,h=l.height/e|0,i=g*h,j={},k,n;for(n in c)k=c[n],k instanceof Array&&(k=k.slice(0)),j[n]=k;var q=[],o=0,m=0;for(n in a)if(k=a[n],k=c[k[0]],k!=null){if(k instanceof Array){var r=k[0],p=k[1];p==null&&(p=r)}else r=p=k;q[m]=n;q[m+1]=r;q[m+2]=p;o+=p-r+1;m+=4}c=SpriteSheetUtils._workingCanvas;c.width=l.width;c.height=Math.ceil(h+o/g)*e;o=SpriteSheetUtils._workingContext;o.drawImage(l,0,0,g*d,h*e,0,0,g*d,h*e);h=i-1;for(m=0;m<q.length;m+=4){n=
q[m];r=q[m+1];p=q[m+2];k=a[n];for(var i=k[1]?-1:1,u=k[2]?-1:1,v=i==-1?d:0,w=u==-1?e:0,s=r;s<=p;s++)h++,o.save(),o.translate(h%g*d+v,(h/g|0)*e+w),o.scale(i,u),o.drawImage(l,s%g*d,(s/g|0)*e,d,e,0,0,d,e),o.restore();j[n]=[h-(p-r),h,k[3]]}l=new Image;l.src=c.toDataURL("image/png");return new SpriteSheet(l.width>0?l:c,d,e,j)};SpriteSheetUtils.frameDataToString=function(b){var a="",l=0,c=0,d=0,e,g;for(g in b){d++;e=b[g];if(e instanceof Array){var h=e[0],i=e[1];i==null&&(i=h);e=e[2];e==null&&(e=g)}else h=
i=e,e=g;a+="\n\t"+g+", start="+h+", end="+i+", next="+e;e==!1?a+=" (stop)":e==g&&(a+=" (loop)");i>l&&(l=i);h<c&&(c=h)}return d+" sequences, min="+c+", max="+l+a};SpriteSheetUtils.extractFrame=function(b,a){var l=b.image,c=b.frameWidth,d=b.frameHeight,e=l.width/c|0;if(isNaN(a))var g=b.frameData[a],a=g instanceof Array?g[0]:g;g=SpriteSheetUtils._workingCanvas;g.width=c;g.height=d;SpriteSheetUtils._workingContext.drawImage(l,a%e*c,(a/e|0)*d,c,d,0,0,c,d);l=new Image;l.src=g.toDataURL("image/png");return l};
l.SpriteSheetUtils=SpriteSheetUtils})(window);
